DROP DATABASE IF EXISTS GESTION_PARKING_HJ;
CREATE DATABASE GESTION_PARKING_HJ;
USE GESTION_PARKING_HJ;

CREATE TABLE PARKING_SALIDA(
ID INT PRIMARY KEY AUTO_INCREMENT,
MATRICULA VARCHAR(7),
TIEMPO_PARKING INT,
TARIFA_APLICADA DOUBLE,
TOTAL_A_PAGAR DOUBLE,
FECHA_SALIDA DATETIME DEFAULT CURRENT_TIMESTAMP
);

<<<<<<< HEAD

CREATE TABLE APARCAR(
ID INT AUTO_INCREMENT PRIMARY KEY,
N_PLAZA INT UNIQUE,
MATRICULA VARCHAR(10),
TIPO_PLAZA ENUM('COCHE','MOTO','FURGONETA'),
FECHA_ENTRADA DATETIME DEFAULT CURRENT_TIMESTAMP
=======
CREATE TABLE VEHICULOS_REGISTRADOS (
    MATRICULA VARCHAR(10) PRIMARY KEY,
    COMBUSTIBLE VARCHAR(50),
    MARCA VARCHAR(50),
    MODELO VARCHAR(50),
    COLOR VARCHAR(50),
    NOMBRE_COMPLETO VARCHAR(100),
    DNI VARCHAR(15)
);


CREATE TABLE COCHE (
	MATRICULA VARCHAR(20) PRIMARY KEY,
    DNI_DUEÑO VARCHAR(10),
    MARCA VARCHAR(50),
    MODELO VARCHAR(70),
    COLOR VARCHAR(30)
);

CREATE TABLE PERSONA (
	NOMBRE_COMPLETO VARCHAR(100),
    DNI VARCHAR(10) PRIMARY KEY
);

CREATE TABLE APARCAMIENTO (
	N_PLAZA INT PRIMARY KEY,
    LIBRE BOOLEAN,
    MATRICULA VARCHAR(20),
    TIPO_PLAZA VARCHAR(20),
    TARIFA_HORA DOUBLE,
    PLAZACARGADORELECTRICO BOOLEAN,
    FECHA_ENTRADA DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PARKING(
N_PARKING INT PRIMARY KEY,
MATRICULA VARCHAR(7),
CANT_PLAZAS INT

>>>>>>> interfaz-grafica
);

-- CONSULTAR SALIDAS PARKING
SELECT * FROM PARKING_SALIDA;
<<<<<<< HEAD

-- CONSULTAR FACTURACION TOTAL
SELECT ROUND(SUM(TOTAL_A_PAGAR), 2) AS FACTURACION FROM PARKING_SALIDA;

-- WORKBENCH SIN CONTRASEÑA
ALTER USER 'root'@'localhost' identified by '';
FLUSH PRIVILEGES;

-- PLAZAS OCUPADAS
SELECT N_PLAZA FROM APARCAR;

-- EJEMPLO PLAZA OCUPADA
INSERT INTO APARCAR (N_PLAZA, MATRICULA, TIPO_PLAZA)
VALUES (3, '1234ABC', 'COCHE');

-- EJEMPLO PLAZA OCUPADA 2
INSERT INTO APARCAR (N_PLAZA, MATRICULA, TIPO_PLAZA)
VALUES (7, '5678XYZ', 'MOTO');
=======
-- CONSULTAR FACTURACION TOTAL
SELECT ROUND(SUM(TOTAL_A_PAGAR), 2) AS FACTURACION FROM PARKING_SALIDA;
>>>>>>> interfaz-grafica
