DROP DATABASE IF EXISTS GESTION_PARKING_HJ;
CREATE DATABASE GESTION_PARKING_HJ;
USE GESTION_PARKING_HJ;

CREATE TABLE PARKING_SALIDA(
ID INT PRIMARY KEY AUTO_INCREMENT,
MATRICULA VARCHAR(7),
TIEMPO_PARKING INT,
TARIFA_APLICADA DOUBLE,
TOTAL_A_PAGAR DOUBLE,
FECHA_SALIDA DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE APARCAR(
ID INT,
N_PLAZA INT PRIMARY KEY,
MATRICULA VARCHAR(7),
TIPO_PLAZA ENUM('COCHE','MOTO','FURGONETA'),
FECHA_ENTRADA DATETIME DEFAULT CURRENT_TIMESTAMP

);

-- CONSULTAR SALIDAS PARKING
SELECT * FROM PARKING_SALIDA;

-- CONSULTAR FACTURACION TOTAL
SELECT ROUND(SUM(TOTAL_A_PAGAR), 2) AS FACTURACION FROM PARKING_SALIDA;

-- WORKBENCH SIN CONTRASEÑA
ALTER USER 'root'@'localhost' identified by '';
FLUSH PRIVILEGES;
