/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantalla;

import com.izv.proyectofinalprogramacion_jorgegarre_higordesouza.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author jorgegarre
 */
public class aparcarVehiculo extends javax.swing.JFrame {

    String matricula;
    String marca;
    String modelo;
    String color;
    String tipoVehiculo;
    String nombreCompleto;
    String dni;
    String tipoCombustible;
    int longitud;

    /**
     * Creates new form Prueba
     */
    public aparcarVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VehiculoSelector = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Matricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Marca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Modelo = new javax.swing.JTextField();
        Color = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkCoche = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        checkMoto = new javax.swing.JRadioButton();
        checkFurgoneta = new javax.swing.JRadioButton();
        Boton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        NombreCompleto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Dni = new javax.swing.JTextField();
        userNombreCompleto = new javax.swing.JTextField();
        userDni = new javax.swing.JTextField();
        inicioBtn = new javax.swing.JButton();
        showTipoVehiculo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("¡Bienvenido al Parking!");

        jLabel2.setText("Introduce tu matrícula");

        Matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculaActionPerformed(evt);
            }
        });

        jLabel3.setText("Introduce la marca");

        Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaActionPerformed(evt);
            }
        });

        jLabel4.setText("Introduce el modelo");

        Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeloActionPerformed(evt);
            }
        });

        Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorActionPerformed(evt);
            }
        });

        jLabel5.setText("Introduce el color");

        VehiculoSelector.add(checkCoche);
        checkCoche.setText("Coche");
        checkCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCocheActionPerformed(evt);
            }
        });

        jLabel7.setText("Introduce tipo de Vehiculo");

        VehiculoSelector.add(checkMoto);
        checkMoto.setText("Moto");
        checkMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMotoActionPerformed(evt);
            }
        });

        VehiculoSelector.add(checkFurgoneta);
        checkFurgoneta.setText("Furgoneta");
        checkFurgoneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFurgonetaActionPerformed(evt);
            }
        });

        Boton.setText("Crear Vehiculo");
        Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActionPerformed(evt);
            }
        });

        jLabel6.setText("Introduce tu nombre Completo");

        NombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCompletoActionPerformed(evt);
            }
        });

        jLabel8.setText("Introduce DNI");

        Dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DniActionPerformed(evt);
            }
        });

        userNombreCompleto.setText("Nombre Completo");
        userNombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNombreCompletoActionPerformed(evt);
            }
        });

        userDni.setText("DNI");

        inicioBtn.setText("Volver al inicio");
        inicioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Matricula)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Marca)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Modelo)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Color)
                    .addComponent(checkCoche)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkMoto)
                    .addComponent(checkFurgoneta))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Boton)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(NombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Dni)
                                            .addComponent(userNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(userDni))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(inicioBtn)
                                        .addGap(102, 102, 102))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel6)
                        .addGap(55, 55, 55))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showTipoVehiculo)
                .addGap(157, 157, 157))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(checkCoche)
                        .addGap(5, 5, 5)
                        .addComponent(checkMoto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton)
                            .addComponent(inicioBtn))))
                .addGap(5, 5, 5)
                .addComponent(checkFurgoneta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(showTipoVehiculo)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculaActionPerformed

    }//GEN-LAST:event_MatriculaActionPerformed

    private void MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaActionPerformed
    }//GEN-LAST:event_MarcaActionPerformed

    private void ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeloActionPerformed
    }//GEN-LAST:event_ModeloActionPerformed

    private void ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorActionPerformed
    }//GEN-LAST:event_ColorActionPerformed

    private void checkCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCocheActionPerformed
        tipoVehiculo = "COCHE";
    }//GEN-LAST:event_checkCocheActionPerformed

    private void checkMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMotoActionPerformed
        tipoVehiculo = "MOTO";
    }//GEN-LAST:event_checkMotoActionPerformed

    private void checkFurgonetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFurgonetaActionPerformed
        tipoVehiculo = "FURGONETA";
    }//GEN-LAST:event_checkFurgonetaActionPerformed

    private void BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActionPerformed

        matricula = Matricula.getText();
        marca = Marca.getText();
        modelo = Modelo.getText();
        color = Color.getText();
        dni = Dni.getText();
        nombreCompleto = NombreCompleto.getText();

        showTipoVehiculo.setText(tipoVehiculo);

        switch (tipoVehiculo.toUpperCase()) {
            case "COCHE":
                SeleccionarCombustibleVehiculo pantalla = new SeleccionarCombustibleVehiculo(this, this);
                pantalla.setLocationRelativeTo(null);
                pantalla.setVisible(true);

                tipoCombustible = pantalla.getTipoCombustible();

                switch (tipoCombustible.trim().toUpperCase()) {
                    case "GASOLINA":

                        try {
                            // Crear objetos
                            Persona pepe = new Persona(nombreCompleto, dni);
                            Combustion coche = new Combustion(tipoCombustible, matricula, pepe, marca, modelo, color);

                            userNombreCompleto.setText(pepe.getNombreCompleto());
                            userDni.setText(pepe.getDni());

                            // Guardar en la base de datos
                            Connection con = DriverManager.getConnection(
                                    "jdbc:mysql://localhost:3306/GESTION_PARKING_HJ", "root", "");

                            String sql = "INSERT INTO VEHICULOS_REGISTRADOS (MATRICULA, COMBUSTIBLE, MARCA, MODELO, COLOR, NOMBRE_COMPLETO, DNI) "
                                    + "VALUES (?, ?, ?, ?, ?, ?, ?)";

                            PreparedStatement ps = con.prepareStatement(sql);
                            ps.setString(1, coche.getMatricula());
                            ps.setString(2, coche.getCombustible());
                            ps.setString(3, coche.getMarca());
                            ps.setString(4, coche.getModelo());
                            ps.setString(5, coche.getColor());
                            ps.setString(6, pepe.getNombreCompleto());
                            ps.setString(7, pepe.getDni());

                            ps.executeUpdate();
                            con.close();

                            System.out.println("Vehículo registrado en la base de datos correctamente.");

                            // Abrir la pantalla de elegir plaza
                            ElegirPlaza elegirPlaza = new ElegirPlaza();
                            elegirPlaza.setLocationRelativeTo(null);
                            elegirPlaza.setVisible(true);
                            this.dispose(); // Cierra la pantalla actual si ya no se necesita

                        } catch (IncorrectNameException | BadDniException | BadMatriculaException | BadCombustibleException e) {
                            PantallaExcepciones pantallaExcept = new PantallaExcepciones(e.getMessage());
                            pantallaExcept.setVisible(true);
                            pantallaExcept.setLocationRelativeTo(null);
                        } catch (SQLException e) {
                            e.printStackTrace(); // Mostrar errores de conexión o SQL
                        }

                        break;
                    case "DIESEL":
                        try {
                            Persona pepe = new Persona(nombreCompleto, dni);
                            Combustion coche = new Combustion(tipoCombustible, matricula, pepe, marca, modelo, color);

                            userNombreCompleto.setText(pepe.getNombreCompleto());
                            userDni.setText(pepe.getDni());

                        } catch (IncorrectNameException | BadDniException | BadMatriculaException | BadCombustibleException e) {
                            PantallaExcepciones pantallaExcept = new PantallaExcepciones(e.getMessage());
                            pantallaExcept.setVisible(true);

                            pantallaExcept.setLocationRelativeTo(null);
                        }
                        break;
                    case "HIBRIDO TOTAL":
                        try {
                            Persona pepe = new Persona(nombreCompleto, dni);
                            Hibrido_total coche = new Hibrido_total(matricula, pepe, marca, modelo, color);

                            userNombreCompleto.setText(pepe.getNombreCompleto());
                            userDni.setText(pepe.getDni());

                        } catch (IncorrectNameException | BadDniException | BadMatriculaException e) {
                            PantallaExcepciones pantallaExcept = new PantallaExcepciones(e.getMessage());
                            pantallaExcept.setVisible(true);
                            pantallaExcept.setLocationRelativeTo(null);
                        }
                        break;
                    case "HIBRIDO ENCHUFABLE":
                        try {
                            Persona pepe = new Persona(nombreCompleto, dni);
                            Hibrido_enchufable coche = new Hibrido_enchufable(matricula, pepe, marca, modelo, color);

                            userNombreCompleto.setText(pepe.getNombreCompleto());
                            userDni.setText(pepe.getDni());

                        } catch (IncorrectNameException | BadDniException | BadMatriculaException e) {
                            PantallaExcepciones pantallaExcept = new PantallaExcepciones(e.getMessage());
                            pantallaExcept.setVisible(true);
                            pantallaExcept.setLocationRelativeTo(null);
                        }
                        break;
                }
                break;
            case "MOTO":
                try {
                    Persona pepe = new Persona(nombreCompleto, dni);
                    Moto moto = new Moto(matricula, pepe, marca, modelo, color);

                    userNombreCompleto.setText(pepe.getNombreCompleto());
                    userDni.setText(pepe.getDni());

                } catch (IncorrectNameException | BadDniException | BadMatriculaException e) {
                    PantallaExcepciones pantallaExcept = new PantallaExcepciones(e.getMessage());
                    pantallaExcept.setVisible(true);
                    pantallaExcept.setLocationRelativeTo(null);
                }
                break;
            case "FURGONETA":
                SeleccionarLongitudFurgoneta pantallaLongitud = new SeleccionarLongitudFurgoneta(this, this);
                pantallaLongitud.setLocationRelativeTo(null);
                pantallaLongitud.setVisible(true);

                longitud = pantallaLongitud.getLongitud();

                try {
                    Persona pepe = new Persona(nombreCompleto, dni);
                    Furgoneta furgoneta = new Furgoneta(longitud, matricula, pepe, marca, modelo, color);

                    userNombreCompleto.setText(pepe.getNombreCompleto());
                    userDni.setText(pepe.getDni());

                } catch (IncorrectNameException | BadDniException | BadMatriculaException | FurgonetaDeMayorLongitudException e) {
                    PantallaExcepciones pantallaExcept = new PantallaExcepciones(e.getMessage());
                    pantallaExcept.setVisible(true);
                    pantallaExcept.setLocationRelativeTo(null);
                }
                break;
            default:
                System.out.println("Tipo de combustible no reconocido: " + tipoCombustible);
                break;

        }


    }//GEN-LAST:event_BotonActionPerformed

    private void DniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DniActionPerformed
    }//GEN-LAST:event_DniActionPerformed

    private void NombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCompletoActionPerformed
    }//GEN-LAST:event_NombreCompletoActionPerformed

    private void inicioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioBtnActionPerformed
        InicioScreen pantalla = new InicioScreen();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        this.dispose();    }//GEN-LAST:event_inicioBtnActionPerformed

    private void userNombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNombreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNombreCompletoActionPerformed

    public void setTipoCombustible(String tipoCombustible) {
        this.tipoCombustible = tipoCombustible;
    }

    /**
     */
    public class Main {

        public static void main(String[] args) {
            javax.swing.SwingUtilities.invokeLater(() -> {
                aparcarVehiculo pantalla = new aparcarVehiculo();
                pantalla.setVisible(true);
                pantalla.setLocationRelativeTo(null); // Centrar ventana
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton;
    private javax.swing.JTextField Color;
    private javax.swing.JTextField Dni;
    private javax.swing.JTextField Marca;
    private javax.swing.JTextField Matricula;
    private javax.swing.JTextField Modelo;
    private javax.swing.JTextField NombreCompleto;
    private javax.swing.ButtonGroup VehiculoSelector;
    private javax.swing.JRadioButton checkCoche;
    private javax.swing.JRadioButton checkFurgoneta;
    private javax.swing.JRadioButton checkMoto;
    private javax.swing.JButton inicioBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel showTipoVehiculo;
    private javax.swing.JTextField userDni;
    private javax.swing.JTextField userNombreCompleto;
    // End of variables declaration//GEN-END:variables
}
