/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantalla;

import com.izv.proyectofinalprogramacion_jorgegarre_higordesouza.*;
import Pantalla.*;
/**
 *
 * @author jorgegarre
 */
public class aparcarVehiculo extends javax.swing.JFrame {
    
    String matricula;
    String marca;
    String modelo;
    String color;
    String tipoVehiculo;
    String nombreCompleto;
    String dni;
    String tipoCombustible;

    /**
     * Creates new form Prueba
     */
    public aparcarVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VehiculoSelector = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Matricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Marca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Modelo = new javax.swing.JTextField();
        Color = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkCoche = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        checkMoto = new javax.swing.JRadioButton();
        checkFurgoneta = new javax.swing.JRadioButton();
        userMatricula = new javax.swing.JTextField();
        userMarca = new javax.swing.JTextField();
        userModelo = new javax.swing.JTextField();
        userColor = new javax.swing.JTextField();
        Boton = new javax.swing.JButton();
        userTipoVehiculo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NombreCompleto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Dni = new javax.swing.JTextField();
        userNombreCompleto = new javax.swing.JTextField();
        userDni = new javax.swing.JTextField();
        inicioBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        userCombustion = new javax.swing.JTextField();
        combustibleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("¡Bienvenido al Parking!");

        jLabel2.setText("Introduce tu matrícula");

        Matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculaActionPerformed(evt);
            }
        });

        jLabel3.setText("Introduce la marca");

        Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaActionPerformed(evt);
            }
        });

        jLabel4.setText("Introduce el modelo");

        Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeloActionPerformed(evt);
            }
        });

        Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorActionPerformed(evt);
            }
        });

        jLabel5.setText("Introduce el color");

        VehiculoSelector.add(checkCoche);
        checkCoche.setText("Coche");
        checkCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCocheActionPerformed(evt);
            }
        });

        jLabel7.setText("Introduce tipo de Vehiculo");

        VehiculoSelector.add(checkMoto);
        checkMoto.setText("Moto");
        checkMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMotoActionPerformed(evt);
            }
        });

        VehiculoSelector.add(checkFurgoneta);
        checkFurgoneta.setText("Furgoneta");
        checkFurgoneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFurgonetaActionPerformed(evt);
            }
        });

        userMatricula.setText("Matrícula");
        userMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMatriculaActionPerformed(evt);
            }
        });

        userMarca.setText("Marca");
        userMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMarcaActionPerformed(evt);
            }
        });

        userModelo.setText("Modelo");
        userModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userModeloActionPerformed(evt);
            }
        });

        userColor.setText("Color");
        userColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userColorActionPerformed(evt);
            }
        });

        Boton.setText("Crear Vehiculo");
        Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActionPerformed(evt);
            }
        });

        userTipoVehiculo.setText("Tipo Vehiculo");
        userTipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTipoVehiculoActionPerformed(evt);
            }
        });

        jLabel6.setText("Introduce tu nombre Completo");

        NombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCompletoActionPerformed(evt);
            }
        });

        jLabel8.setText("Introduce DNI");

        Dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DniActionPerformed(evt);
            }
        });

        userNombreCompleto.setText("Nombre Completo");
        userNombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNombreCompletoActionPerformed(evt);
            }
        });

        userDni.setText("DNI");

        inicioBtn.setText("Volver al inicio");
        inicioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioBtnActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        userCombustion.setText("Combustion");
        userCombustion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCombustionActionPerformed(evt);
            }
        });

        combustibleLabel.setText("Combustible");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Matricula)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Marca)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Modelo)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Color)
                    .addComponent(checkCoche)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkMoto)
                    .addComponent(checkFurgoneta))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(userMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userModelo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userColor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userTipoVehiculo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Boton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(userMatricula))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(NombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Dni)
                                                    .addComponent(userNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                    .addComponent(userDni)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(userCombustion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inicioBtn)
                                            .addComponent(combustibleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel6)))
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userCombustion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(checkCoche)
                        .addGap(5, 5, 5)
                        .addComponent(checkMoto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton)
                            .addComponent(inicioBtn))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(checkFurgoneta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(combustibleLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculaActionPerformed
        matricula = Matricula.getText();
    }//GEN-LAST:event_MatriculaActionPerformed

    private void MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaActionPerformed
        marca = Marca.getText();
    }//GEN-LAST:event_MarcaActionPerformed

    private void ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeloActionPerformed
        modelo = Modelo.getText();
    }//GEN-LAST:event_ModeloActionPerformed

    private void ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorActionPerformed
        color = Color.getText();
    }//GEN-LAST:event_ColorActionPerformed

    private void checkCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCocheActionPerformed
        tipoVehiculo = "Coche";
    }//GEN-LAST:event_checkCocheActionPerformed

    private void checkMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMotoActionPerformed
        tipoVehiculo = "Moto";
    }//GEN-LAST:event_checkMotoActionPerformed

    private void checkFurgonetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFurgonetaActionPerformed
        tipoVehiculo = "Furgoneta";
    }//GEN-LAST:event_checkFurgonetaActionPerformed

    private void userMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userMatriculaActionPerformed

    private void userMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userMarcaActionPerformed

    private void userModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userModeloActionPerformed

    private void userColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userColorActionPerformed

    private void BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActionPerformed
            
        switch (tipoVehiculo.toUpperCase()) {
            case "COCHE":
                    SeleccionarCombustibleVehiculo pantalla = new SeleccionarCombustibleVehiculo(this);
                    pantalla.setVisible(true);
                    pantalla.setLocationRelativeTo(null);
                    combustibleLabel.setText(tipoCombustible);
                    
                   
                
        }
    

        try {
            Persona pepe = new Persona(nombreCompleto, dni);
            Combustion coche = new Combustion(tipoCombustible, matricula, pepe, marca, modelo, color);
            userMatricula.setText(coche.getMatricula());
            userModelo.setText(coche.getModelo());
            userMarca.setText(coche.getMarca());
            userColor.setText(coche.getColor());
            userTipoVehiculo.setText(coche.getTipoVehiculo());
            userCombustion.setText(coche.getCombustible());
            
            userNombreCompleto.setText(pepe.getNombreCompleto());
            userDni.setText(pepe.getDni());
            
            
        } catch (IncorrectNameException | BadDniException | BadMatriculaException | BadCombustibleException e) {
            PantallaExcepciones pantalla = new PantallaExcepciones(e.getMessage());
            pantalla.setVisible(true);
            pantalla.setLocationRelativeTo(null);
        }
        
        
    }//GEN-LAST:event_BotonActionPerformed

    private void userTipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTipoVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTipoVehiculoActionPerformed

    private void DniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DniActionPerformed
        dni = Dni.getText();
    }//GEN-LAST:event_DniActionPerformed

    private void NombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCompletoActionPerformed
        nombreCompleto = NombreCompleto.getText();
    }//GEN-LAST:event_NombreCompletoActionPerformed

    private void inicioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioBtnActionPerformed
        InicioScreen pantalla = new InicioScreen();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        this.dispose();    }//GEN-LAST:event_inicioBtnActionPerformed

    private void userNombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNombreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNombreCompletoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SeleccionarCombustibleVehiculo pantalla = new SeleccionarCombustibleVehiculo(this);
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        combustibleLabel.setText(tipoCombustible);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void userCombustionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCombustionActionPerformed
    }//GEN-LAST:event_userCombustionActionPerformed

    public void setTipoCombustible(String tipoCombustible) {
        this.tipoCombustible = tipoCombustible;
    }


    
    
    /**
     */
    public class Main {
     public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            aparcarVehiculo pantalla = new aparcarVehiculo();
            pantalla.setVisible(true);
            pantalla.setLocationRelativeTo(null); // Centrar ventana
        });
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton;
    private javax.swing.JTextField Color;
    private javax.swing.JTextField Dni;
    private javax.swing.JTextField Marca;
    private javax.swing.JTextField Matricula;
    private javax.swing.JTextField Modelo;
    private javax.swing.JTextField NombreCompleto;
    private javax.swing.ButtonGroup VehiculoSelector;
    private javax.swing.JRadioButton checkCoche;
    private javax.swing.JRadioButton checkFurgoneta;
    private javax.swing.JRadioButton checkMoto;
    private javax.swing.JLabel combustibleLabel;
    private javax.swing.JButton inicioBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField userColor;
    private javax.swing.JTextField userCombustion;
    private javax.swing.JTextField userDni;
    private javax.swing.JTextField userMarca;
    private javax.swing.JTextField userMatricula;
    private javax.swing.JTextField userModelo;
    private javax.swing.JTextField userNombreCompleto;
    private javax.swing.JTextField userTipoVehiculo;
    // End of variables declaration//GEN-END:variables
}
