/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantalla;

import com.izv.proyectofinalprogramacion_jorgegarre_higordesouza.*;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class Contabilidad extends javax.swing.JFrame {

    /**
     * Creates new form contabilidad
     */
    public Contabilidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inicioBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInforme = new javax.swing.JTextArea();
        btnInforme = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTotalFacturacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("SALIDAS DEL PARKING");

        inicioBtn.setText("Volver al inicio");
        inicioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioBtnActionPerformed(evt);
            }
        });

        txtInforme.setColumns(20);
        txtInforme.setRows(5);
        jScrollPane1.setViewportView(txtInforme);

        btnInforme.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnInforme.setText("Mostrar Informe");
        btnInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeActionPerformed(evt);
            }
        });

        btnExportar.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnExportar.setText("Exportar informe");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        jLabel2.setText("TOTAL FACTURACIÓN:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inicioBtn)
                                .addGap(32, 32, 32))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(24, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnInforme)
                        .addGap(28, 28, 28)
                        .addComponent(btnExportar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotalFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(inicioBtn)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioBtnActionPerformed
        InicioScreen pantalla = new InicioScreen();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_inicioBtnActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        // Ruta y nombre del archivo a exportar
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        String fechaActual = sdf.format(new Date());

        // Nombre del archivo con la fecha
        String nombreArchivo = "SalidasParking-" + fechaActual + ".txt";

        // Obtener el contenido del JTextArea (txtInforme)
        String contenidoInforme = txtInforme.getText();

        // Verificar que hay contenido
        if (contenidoInforme.isEmpty()) {
            JOptionPane.showMessageDialog(null, "⚠️ No hay ningún informe para exportar.");
            return;
        }

        // Intentar escribir el archivo
        try ( BufferedWriter writer = new BufferedWriter(new FileWriter(nombreArchivo))) {
            writer.write(contenidoInforme);
            JOptionPane.showMessageDialog(null, "✅ Informe exportado correctamente a " + nombreArchivo);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "❌ Error al exportar el informe.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    private void btnInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeActionPerformed
        // TODO add your handling code here:
        StringBuilder informeCompleto = new StringBuilder();

        try ( Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/GESTION_PARKING_HJ", "root", "");  
                Statement stmt = conn.createStatement();  ResultSet rs = stmt.executeQuery("SELECT * FROM PARKING_SALIDA ORDER BY fecha_salida")) {

            // Encabezado del informe
            informeCompleto.append(String.format("%-5s %-15s %-17s %-17s %-20s\n",
                    "ID", "Tiempo (min)", "Tarifa (€)", "Total (€)", "Fecha de salida"));
            informeCompleto.append("\n");

            while (rs.next()) {
                int id = rs.getInt("ID");
                int tiempo_parking = rs.getInt("Tiempo_Parking");
                double tarifa_aplicada = rs.getDouble("Tarifa_aplicada");
                double total_a_pagar = rs.getDouble("total_a_pagar");
                String fecha_salida = rs.getString("fecha_salida");

                // Añadir datos con formato tabulado
                informeCompleto.append(String.format("%-5d %-15d %-17.2f %-17.2f %-20s\n",
                        id, tiempo_parking, tarifa_aplicada, total_a_pagar, fecha_salida));
            }
            txtInforme.setEditable(false);

            txtInforme.setText(informeCompleto.toString());

        } catch (SQLException e) {
            System.out.println("❌ Error al consultar la base de datos:");
            e.printStackTrace();
        }

        try ( Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/GESTION_PARKING_HJ", "root", "");  Statement stmt = conn.createStatement();  ResultSet rs = stmt.executeQuery("SELECT ROUND(SUM(TOTAL_A_PAGAR), 2) AS FACTURACION FROM PARKING_SALIDA;")) {

            // Verificamos si hay resultados en el ResultSet
            if (rs.next()) {
                // Recuperamos el valor de FACTURACION
                double facturacion = rs.getDouble("FACTURACION");

                // Asignamos el valor a txtInforme
                txtTotalFacturacion.setText(facturacion + " €");
            } else {
                txtTotalFacturacion.setText("No se encontró ningún dato.");
            }
            txtTotalFacturacion.setEditable(false);

        } catch (SQLException e) {
            System.out.println("❌ Error al consultar la base de datos:");
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnInformeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            Contabilidad pantalla = new Contabilidad();
            pantalla.setVisible(true);
            pantalla.setLocationRelativeTo(null);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnInforme;
    private javax.swing.JButton inicioBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtInforme;
    private javax.swing.JTextField txtTotalFacturacion;
    // End of variables declaration//GEN-END:variables
}
