/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantalla;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class ElegirPlaza extends javax.swing.JFrame {

    private int plazaSeleccionada = -1;



    /**
     * Creates new form ElegirPlaza
     */
    public ElegirPlaza() {
        initComponents();
    }

    private boolean plazaOcupada(int numeroPlaza) {
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/GESTION_PARKING_HJ", "root", "");
         PreparedStatement stmt = conn.prepareStatement("SELECT COUNT(*) FROM APARCAR WHERE N_PLAZA = ?")) {

        stmt.setInt(1, numeroPlaza);
        try (ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                return rs.getInt(1) > 0; // Hay al menos un registro para esa plaza
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
    }
    return true; // Si falla la consulta, asumimos ocupada por seguridad
}
    
    
public int getPlazaSeleccionada() {
    return plazaSeleccionada;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Parkingbtn17 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Parkingbtn18 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Parkingbtn21 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Parkingbtn22 = new javax.swing.JButton();
        Parkingbtn23 = new javax.swing.JButton();
        Parkingbtn24 = new javax.swing.JButton();
        Parkingbtn25 = new javax.swing.JButton();
        Parkingbtn26 = new javax.swing.JButton();
        Salirbtn = new javax.swing.JButton();
        Parkingbtn27 = new javax.swing.JButton();
        Parkingbtn30 = new javax.swing.JButton();
        Parkingbtn9 = new javax.swing.JButton();
        Parkingbtn31 = new javax.swing.JButton();
        Parkingbtn10 = new javax.swing.JButton();
        Parkingbtn32 = new javax.swing.JButton();
        Parkingbtn33 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Parkingbtn34 = new javax.swing.JButton();
        Parkingbtn11 = new javax.swing.JButton();
        Parkingbtn29 = new javax.swing.JButton();
        Parkingbtn12 = new javax.swing.JButton();
        Parkingbtn28 = new javax.swing.JButton();
        Parkingbtn13 = new javax.swing.JButton();
        Parkingbtn35 = new javax.swing.JButton();
        Parkingbtn14 = new javax.swing.JButton();
        Parkingbtn36 = new javax.swing.JButton();
        Parkingbtn15 = new javax.swing.JButton();
        Parkingbtn16 = new javax.swing.JButton();
        Parkingbtn1 = new javax.swing.JButton();
        Parkingbtn2 = new javax.swing.JButton();
        Parkingbtn3 = new javax.swing.JButton();
        Parkingbtn4 = new javax.swing.JButton();
        Parkingbtn5 = new javax.swing.JButton();
        Parkingbtn6 = new javax.swing.JButton();
        Parkingbtn7 = new javax.swing.JButton();
        Parkingbtn8 = new javax.swing.JButton();
        Parkingbtn37 = new javax.swing.JButton();
        Parkingbtn38 = new javax.swing.JButton();
        Parkingbtn20 = new javax.swing.JButton();
        Parkingbtn39 = new javax.swing.JButton();
        Parkingbtn19 = new javax.swing.JButton();
        Parkingbtn40 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Parkingbtn17.setText("17");
        Parkingbtn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn17ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("PLAZAS DE COCHE");

        Parkingbtn18.setText("18");
        Parkingbtn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn18ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("PLAZAS DE MOTO");

        Parkingbtn21.setText("21");
        Parkingbtn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn21ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("PLAZAS DE FURGONETA");

        Parkingbtn22.setText("22");
        Parkingbtn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn22ActionPerformed(evt);
            }
        });

        Parkingbtn23.setText("23");

        Parkingbtn24.setText("24");

        Parkingbtn25.setText("25");

        Parkingbtn26.setText("26");

        Salirbtn.setText("Volver al inicio");
        Salirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirbtnActionPerformed(evt);
            }
        });

        Parkingbtn27.setText("27");

        Parkingbtn30.setText("30");

        Parkingbtn9.setText("9");
        Parkingbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn9ActionPerformed(evt);
            }
        });

        Parkingbtn31.setText("31");

        Parkingbtn10.setText("10");
        Parkingbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn10ActionPerformed(evt);
            }
        });

        Parkingbtn32.setText("32");

        Parkingbtn33.setText("33");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PLAZAS DEL PARKING");

        Parkingbtn34.setText("34");

        Parkingbtn11.setText("11");
        Parkingbtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn11ActionPerformed(evt);
            }
        });

        Parkingbtn29.setText("29");

        Parkingbtn12.setText("12");
        Parkingbtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn12ActionPerformed(evt);
            }
        });

        Parkingbtn28.setText("28");

        Parkingbtn13.setText("13");
        Parkingbtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn13ActionPerformed(evt);
            }
        });

        Parkingbtn35.setText("35");

        Parkingbtn14.setText("14");
        Parkingbtn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn14ActionPerformed(evt);
            }
        });

        Parkingbtn36.setText("36");
        Parkingbtn36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn36ActionPerformed(evt);
            }
        });

        Parkingbtn15.setText("15");
        Parkingbtn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn15ActionPerformed(evt);
            }
        });

        Parkingbtn16.setText("16");
        Parkingbtn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn16ActionPerformed(evt);
            }
        });

        Parkingbtn1.setText("1");
        Parkingbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn1ActionPerformed(evt);
            }
        });

        Parkingbtn2.setText("2");
        Parkingbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn2ActionPerformed(evt);
            }
        });

        Parkingbtn3.setText("3");
        Parkingbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn3ActionPerformed(evt);
            }
        });

        Parkingbtn4.setText("4");
        Parkingbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn4ActionPerformed(evt);
            }
        });

        Parkingbtn5.setText("5");
        Parkingbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn5ActionPerformed(evt);
            }
        });

        Parkingbtn6.setText("6");
        Parkingbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn6ActionPerformed(evt);
            }
        });

        Parkingbtn7.setText("7");
        Parkingbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn7ActionPerformed(evt);
            }
        });

        Parkingbtn8.setText("8");
        Parkingbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn8ActionPerformed(evt);
            }
        });

        Parkingbtn37.setText("37");

        Parkingbtn38.setText("38");

        Parkingbtn20.setText("20");
        Parkingbtn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn20ActionPerformed(evt);
            }
        });

        Parkingbtn39.setText("39");

        Parkingbtn19.setText("19");
        Parkingbtn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parkingbtn19ActionPerformed(evt);
            }
        });

        Parkingbtn40.setText("40");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Parkingbtn32, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Parkingbtn28, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Parkingbtn29, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Parkingbtn21, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Parkingbtn22, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Parkingbtn30, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Parkingbtn31, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Parkingbtn23, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(Parkingbtn24, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(27, 27, 27)
                                        .addComponent(Parkingbtn25, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Parkingbtn26, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Parkingbtn33, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Parkingbtn34, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Parkingbtn27, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(Salirbtn)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Parkingbtn35, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(Parkingbtn36, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(Parkingbtn37, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(Parkingbtn38, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Parkingbtn39, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Parkingbtn40, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Parkingbtn11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Parkingbtn12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Parkingbtn13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(Parkingbtn14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Parkingbtn15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(Parkingbtn16, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Parkingbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Parkingbtn17, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Parkingbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Parkingbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Parkingbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Parkingbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Parkingbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Parkingbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Parkingbtn18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parkingbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Parkingbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Parkingbtn19, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Parkingbtn20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Parkingbtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Parkingbtn10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parkingbtn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Parkingbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Parkingbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Parkingbtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parkingbtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parkingbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parkingbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parkingbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parkingbtn6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Parkingbtn19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parkingbtn16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parkingbtn15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parkingbtn14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parkingbtn13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parkingbtn12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parkingbtn11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parkingbtn20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Parkingbtn17, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Parkingbtn18, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Parkingbtn21)
                    .addComponent(Parkingbtn22)
                    .addComponent(Parkingbtn23)
                    .addComponent(Parkingbtn24)
                    .addComponent(Parkingbtn25)
                    .addComponent(Parkingbtn26)
                    .addComponent(Parkingbtn27))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Parkingbtn28)
                    .addComponent(Parkingbtn29)
                    .addComponent(Parkingbtn30)
                    .addComponent(Parkingbtn31)
                    .addComponent(Parkingbtn32)
                    .addComponent(Parkingbtn33)
                    .addComponent(Parkingbtn34))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Parkingbtn35, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Parkingbtn36, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Parkingbtn37, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Parkingbtn38, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Parkingbtn39, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Parkingbtn40, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(Salirbtn)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirbtnActionPerformed
        InicioScreen pantalla = new InicioScreen();
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_SalirbtnActionPerformed

    private void Parkingbtn36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Parkingbtn36ActionPerformed

    private void Parkingbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn1ActionPerformed
    int numeroPlaza = 1;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }    }//GEN-LAST:event_Parkingbtn1ActionPerformed

    private void Parkingbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn2ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 2;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn2ActionPerformed

    private void Parkingbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn3ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 3;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn3ActionPerformed

    private void Parkingbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn4ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 4;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn4ActionPerformed

    private void Parkingbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn5ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 5;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn5ActionPerformed

    private void Parkingbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn6ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 6;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn6ActionPerformed

    private void Parkingbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn7ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 7;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn7ActionPerformed

    private void Parkingbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn8ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 8;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn8ActionPerformed

    private void Parkingbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn9ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 9;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn9ActionPerformed

    private void Parkingbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn10ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 10;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn10ActionPerformed

    private void Parkingbtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn11ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 11;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn11ActionPerformed

    private void Parkingbtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn12ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 12;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn12ActionPerformed

    private void Parkingbtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn13ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 13;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn13ActionPerformed

    private void Parkingbtn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn14ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 14;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn14ActionPerformed

    private void Parkingbtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn15ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 15;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn15ActionPerformed

    private void Parkingbtn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn16ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 16;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn16ActionPerformed

    private void Parkingbtn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn17ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 17;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn17ActionPerformed

    private void Parkingbtn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn18ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 18;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn18ActionPerformed

    private void Parkingbtn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn19ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 19 ;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn19ActionPerformed

    private void Parkingbtn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn20ActionPerformed
        // TODO add your handling code here:
         int numeroPlaza = 20;

    if (plazaOcupada(numeroPlaza)) {
        JOptionPane.showMessageDialog(this, "La plaza " + numeroPlaza + " ya está ocupada.", "Plaza Ocupada", JOptionPane.ERROR_MESSAGE);
    } else {
        plazaSeleccionada = numeroPlaza;
        this.dispose(); // Cierra la ventana después de seleccionar
    }
    }//GEN-LAST:event_Parkingbtn20ActionPerformed

    private void Parkingbtn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Parkingbtn21ActionPerformed

    private void Parkingbtn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parkingbtn22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Parkingbtn22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElegirPlaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElegirPlaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElegirPlaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElegirPlaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElegirPlaza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Parkingbtn1;
    private javax.swing.JButton Parkingbtn10;
    private javax.swing.JButton Parkingbtn11;
    private javax.swing.JButton Parkingbtn12;
    private javax.swing.JButton Parkingbtn13;
    private javax.swing.JButton Parkingbtn14;
    private javax.swing.JButton Parkingbtn15;
    private javax.swing.JButton Parkingbtn16;
    private javax.swing.JButton Parkingbtn17;
    private javax.swing.JButton Parkingbtn18;
    private javax.swing.JButton Parkingbtn19;
    private javax.swing.JButton Parkingbtn2;
    private javax.swing.JButton Parkingbtn20;
    private javax.swing.JButton Parkingbtn21;
    private javax.swing.JButton Parkingbtn22;
    private javax.swing.JButton Parkingbtn23;
    private javax.swing.JButton Parkingbtn24;
    private javax.swing.JButton Parkingbtn25;
    private javax.swing.JButton Parkingbtn26;
    private javax.swing.JButton Parkingbtn27;
    private javax.swing.JButton Parkingbtn28;
    private javax.swing.JButton Parkingbtn29;
    private javax.swing.JButton Parkingbtn3;
    private javax.swing.JButton Parkingbtn30;
    private javax.swing.JButton Parkingbtn31;
    private javax.swing.JButton Parkingbtn32;
    private javax.swing.JButton Parkingbtn33;
    private javax.swing.JButton Parkingbtn34;
    private javax.swing.JButton Parkingbtn35;
    private javax.swing.JButton Parkingbtn36;
    private javax.swing.JButton Parkingbtn37;
    private javax.swing.JButton Parkingbtn38;
    private javax.swing.JButton Parkingbtn39;
    private javax.swing.JButton Parkingbtn4;
    private javax.swing.JButton Parkingbtn40;
    private javax.swing.JButton Parkingbtn5;
    private javax.swing.JButton Parkingbtn6;
    private javax.swing.JButton Parkingbtn7;
    private javax.swing.JButton Parkingbtn8;
    private javax.swing.JButton Parkingbtn9;
    private javax.swing.JButton Salirbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
